spring.application.name=rrhh-service

# Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/rrhh_db
spring.datasource.username=user_rrhh
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
