DROP TABLE IF EXISTS empleados;

CREATE TABLE empleados (
                           id BIGSERIAL PRIMARY KEY,
                           nombre VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           cargo VARCHAR(255) NOT NULL,
                           horas_asignadas INTEGER NOT NULL,
                           capacidad_maxima INTEGER NOT NULL DEFAULT 45
);

INSERT INTO empleados (nombre, email, cargo, horas_asignadas, capacidad_maxima) VALUES
                                                                                    ('Rodrigo Gallardo', 'r.gallardo@innovatech.cl', 'DEVELOPER_LEAD', 20, 45),
                                                                                    ('Ana María Silva', 'a.silva@innovatech.cl', 'UX_DESIGNER', 15, 45),
                                                                                    ('Carlos Iturra', 'c.iturra@innovatech.cl', 'DEVELOPER_QA', 45, 45),
                                                                                    ('María José Palma', 'mj.palma@innovatech.cl', 'DEVELOPER_ARCHITECT', 5, 45),
                                                                                    ('Sebastián Muñoz', 's.munoz@innovatech.cl', 'DEVELOPER_BACKEND', 40, 45),
                                                                                    ('Valentina Rojas', 'v.rojas@innovatech.cl', 'DEVELOPER_FRONTEND', 35, 45),
                                                                                    ('Andrés Morales', 'a.morales@innovatech.cl', 'DEVELOPER_FULLSTACK', 45, 45),
                                                                                    ('Camila Fuentes', 'c.fuentes@innovatech.cl', 'DEVELOPER_QA', 20, 45),
                                                                                    ('Diego Valenzuela', 'd.valenzuela@innovatech.cl', 'DEVELOPER_MANAGER', 30, 45),
                                                                                    ('Fernanda Bravo', 'f.bravo@innovatech.cl', 'DEVELOPER_PO', 12, 45),
                                                                                    ('Gabriel Sepúlveda', 'g.sepulveda@innovatech.cl', 'DEVELOPER_DEVOPS', 40, 45),
                                                                                    ('Isidora Castro', 'i.castro@innovatech.cl', 'DEVELOPER_CLOUD', 22, 45),
                                                                                    ('Matías Figueroa', 'm.figueroa@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Javiera Reyes', 'j.reyes@innovatech.cl', 'UX_DESIGNER_RESEARCH', 18, 45),
                                                                                    ('Nicolás Vera', 'n.veas@innovatech.cl', 'DEVELOPER_FRONTEND', 40, 45),
                                                                                    ('Francisca Soto', 'f.soto@innovatech.cl', 'DEVELOPER_SCRUM', 25, 45),
                                                                                    ('Ricardo Lagos', 'r.lagos@innovatech.cl', 'DEVELOPER_SECURITY', 45, 45),
                                                                                    ('Bárbara Herrera', 'b.herrera@innovatech.cl', 'DEVELOPER_DATA', 0, 45),
                                                                                    ('Felipe Paredes', 'f.paredes@innovatech.cl', 'DEVELOPER_BACKEND', 38, 45),
                                                                                    ('Loreto Espinoza', 'l.espinoza@innovatech.cl', 'DEVELOPER_FRONTEND', 42, 45),
                                                                                    ('Cristian Salazar', 'c.salazar@innovatech.cl', 'DEVELOPER_QA', 45, 45),
                                                                                    ('Antonia Guzmán', 'a.guzman@innovatech.cl', 'UX_DESIGNER', 10, 45),
                                                                                    ('Joaquín Saavedra', 'j.saavedra@innovatech.cl', 'DEVELOPER_MOBILE', 35, 45),
                                                                                    ('Daniela Carrasco', 'd.carrasco@innovatech.cl', 'DEVELOPER_BACKEND', 40, 45),
                                                                                    ('Manuel Pizarro', 'm.pizarro@innovatech.cl', 'DEVELOPER_FULLSTACK', 45, 45),
                                                                                    ('Karla Henríquez', 'k.henriquez@innovatech.cl', 'UX_DESIGNER_PRODUCT', 15, 45),
                                                                                    ('Esteban Donoso', 'e.donoso@innovatech.cl', 'DEVELOPER_DEVOPS', 33, 45),
                                                                                    ('Natalia Jara', 'n.jara@innovatech.cl', 'DEVELOPER_QA', 20, 45),
                                                                                    ('Ignacio Godoy', 'i.godoy@innovatech.cl', 'DEVELOPER_CLOUD', 45, 45),
                                                                                    ('Paola Venegas', 'p.venegas@innovatech.cl', 'DEVELOPER_BACKEND', 30, 45),
                                                                                    ('Héctor Ortiz', 'h.ortiz@innovatech.cl', 'DEVELOPER_FRONTEND', 40, 45),
                                                                                    ('Constanza Leiva', 'c.leiva@innovatech.cl', 'UX_DESIGNER_WRITER', 12, 45),
                                                                                    ('Víctor Méndez', 'v.ortiz@innovatech.cl', 'DEVELOPER_SECURITY', 45, 45),
                                                                                    ('Monserrat Rivas', 'm.rivas@innovatech.cl', 'DEVELOPER_DATA', 28, 45),
                                                                                    ('Álvaro Peña', 'a.pena@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Sofía Cáceres', 's.caceres@innovatech.cl', 'DEVELOPER_FRONTEND', 20, 45),
                                                                                    ('Hugo Navarro', 'h.navarro@innovatech.cl', 'DEVELOPER_QA', 45, 45),
                                                                                    ('Pilar Vidal', 'p.vidal@innovatech.cl', 'DEVELOPER_MANAGER', 15, 45),
                                                                                    ('Samuel Arancibia', 's.arancibia@innovatech.cl', 'DEVELOPER_ARCHITECT', 10, 45),
                                                                                    ('Teresa Maturana', 't.maturana@innovatech.cl', 'DEVELOPER_BACKEND', 40, 45),
                                                                                    ('Jorge Farías', 'j.farias@innovatech.cl', 'DEVELOPER_FRONTEND', 35, 45),
                                                                                    ('Elena Santibáñez', 'e.santibanez@innovatech.cl', 'UX_DESIGNER', 45, 45),
                                                                                    ('Patricio Toledo', 'p.toledo@innovatech.cl', 'DEVELOPER_FULLSTACK', 22, 45),
                                                                                    ('Claudia Miranda', 'c.miranda@innovatech.cl', 'DEVELOPER_QA', 40, 45),
                                                                                    ('Raúl Poblete', 'r.poblete@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Andrea Varas', 'a.varas@innovatech.cl', 'DEVELOPER_MOBILE', 30, 45),
                                                                                    ('Luis Guerra', 'l.guerra@innovatech.cl', 'DEVELOPER_CLOUD', 5, 45),
                                                                                    ('Verónica Lobo', 'v.guerra@innovatech.cl', 'DEVELOPER_FRONTEND', 40, 45),
                                                                                    ('Oscar Osorio', 'o.osorio@innovatech.cl', 'DEVELOPER_DEVOPS', 45, 45),
                                                                                    ('Mónica Beltrán', 'm.osorio@innovatech.cl', 'UX_DESIGNER_ANALYST', 15, 45),
                                                                                    ('Eduardo Marín', 'e.marin@innovatech.cl', 'DEVELOPER_BACKEND', 35, 45),
                                                                                    ('Lucía Campos', 'l.marin@innovatech.cl', 'DEVELOPER_QA', 45, 45),
                                                                                    ('Bernardo O’Higgins', 'b.ohiggins@innovatech.cl', 'DEVELOPER_LEAD', 10, 45),
                                                                                    ('Ximena Lagos', 'x.lagos@innovatech.cl', 'DEVELOPER_FRONTEND', 30, 45),
                                                                                    ('Renato Tapia', 'r.tapia@innovatech.cl', 'DEVELOPER_FULLSTACK', 45, 45),
                                                                                    ('Silvia Quintana', 's.quintana@innovatech.cl', 'DEVELOPER_PO', 20, 45),
                                                                                    ('Gonzalo Ibarra', 'g.ibarra@innovatech.cl', 'DEVELOPER_CLOUD', 45, 45),
                                                                                    ('Tatiana Flores', 't.flores@innovatech.cl', 'DEVELOPER_BACKEND', 12, 45),
                                                                                    ('Mario Bros', 'm.flores@innovatech.cl', 'DEVELOPER_GAME', 40, 45),
                                                                                    ('Sonia Garrido', 's.flores@innovatech.cl', 'DEVELOPER_FRONTEND', 45, 45),
                                                                                    ('Emilio Zuñiga', 'e.zuniga@innovatech.cl', 'DEVELOPER_SECURITY', 25, 45),
                                                                                    ('Florencia Araya', 'f.araya@innovatech.cl', 'UX_DESIGNER', 0, 45),
                                                                                    ('Claudio Palma', 'c.palma@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Julia Moreno', 'j.moreno@innovatech.cl', 'DEVELOPER_QA', 38, 45),
                                                                                    ('Fabián Pinto', 'f.pinto@innovatech.cl', 'DEVELOPER_FRONTEND', 40, 45),
                                                                                    ('Karina Riveros', 'k.pinto@innovatech.cl', 'DEVELOPER_ANALYST', 15, 45),
                                                                                    ('Benjamín Carvajal', 'b.carvajal@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Olga Tello', 'o.carvajal@innovatech.cl', 'UX_DESIGNER_RESEARCH', 22, 45),
                                                                                    ('Hernán Cortés', 'h.cortes@innovatech.cl', 'DEVELOPER_FULLSTACK', 40, 45),
                                                                                    ('Sara Maldonado', 's.maldonado@innovatech.cl', 'DEVELOPER_MANAGER', 45, 45),
                                                                                    ('Andrés Iniesta', 'a.iniesta@innovatech.cl', 'DEVELOPER_BACKEND', 10, 45),
                                                                                    ('Marta Sánchez', 'm.sanchez@innovatech.cl', 'DEVELOPER_FRONTEND', 35, 45),
                                                                                    ('César Vallejo', 'c.vallejo@innovatech.cl', 'DEVELOPER_QA', 45, 45),
                                                                                    ('Beatriz Pinzón', 'b.vallejo@innovatech.cl', 'DEVELOPER_PO', 20, 45),
                                                                                    ('Lorenzo de Médici', 'l.medici@innovatech.cl', 'DEVELOPER_ARCHITECT', 5, 45),
                                                                                    ('Victoria Beckham', 'v.beckham@innovatech.cl', 'UX_DESIGNER_UI', 45, 45),
                                                                                    ('David Pizarro', 'd.pizarro@innovatech.cl', 'DEVELOPER_BACKEND', 30, 45),
                                                                                    ('Alejandra Azcárate', 'a.azcarate@innovatech.cl', 'DEVELOPER_CLOUD', 45, 45),
                                                                                    ('Iván Zamorano', 'i.zamorano@innovatech.cl', 'DEVELOPER_QA', 15, 45),
                                                                                    ('Marcelo Salas', 'm.zamorano@innovatech.cl', 'DEVELOPER_DEVOPS', 40, 45),
                                                                                    ('Eliana Hernández', 'e.hernandez@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Rodrigo Salinas', 'r.hernandez@innovatech.cl', 'DEVELOPER_FRONTEND', 12, 45),
                                                                                    ('Erika Olivera', 'e.olivera@innovatech.cl', 'DEVELOPER_COORDINATOR', 45, 45),
                                                                                    ('Tomás González', 't.olivera@innovatech.cl', 'DEVELOPER_FULLSTACK', 25, 45),
                                                                                    ('Nicole Moreno', 'n.olivera@innovatech.cl', 'DEVELOPER_QA', 40, 45),
                                                                                    ('Fernando Ubiergo', 'f.ubiergo@innovatech.cl', 'UX_DESIGNER_LEAD', 45, 45),
                                                                                    ('Myriam Hernández', 'm.ubiergo@innovatech.cl', 'DEVELOPER_BACKEND', 20, 45),
                                                                                    ('Américo Vespucio', 'a.vespucio@innovatech.cl', 'DEVELOPER_ARCHITECT', 45, 45),
                                                                                    ('Javiera Parra', 'j.parra@innovatech.cl', 'DEVELOPER_FRONTEND', 33, 45),
                                                                                    ('Luis Jara', 'l.jara@innovatech.cl', 'DEVELOPER_QA', 40, 45),
                                                                                    ('Tonka Tomicic', 't.tomicic@innovatech.cl', 'DEVELOPER_STRATEGIST', 15, 45),
                                                                                    ('Felipe Camiroaga', 'f.camiroaga@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Soledad Onetto', 's.tomicic@innovatech.cl', 'DEVELOPER_COMMUNICATIONS', 22, 45),
                                                                                    ('Don Francisco', 'd.francisco@innovatech.cl', 'DEVELOPER_CEO', 5, 45),
                                                                                    ('Cecilia Bolocco', 'c.bolocco@innovatech.cl', 'DEVELOPER_PRODUCT', 45, 45),
                                                                                    ('Stefan Kramer', 's.kramer@innovatech.cl', 'DEVELOPER_SUPPORT', 40, 45),
                                                                                    ('Bombo Fica', 'b.kramer@innovatech.cl', 'DEVELOPER_QA', 10, 45),
                                                                                    ('Sergio Lagos', 's.lagos2@innovatech.cl', 'DEVELOPER_FRONTEND', 45, 45),
                                                                                    ('Diana Bolocco', 'd.bolocco@innovatech.cl', 'UX_DESIGNER', 35, 45),
                                                                                    ('Rafael Araneda', 'r.araneda@innovatech.cl', 'DEVELOPER_BACKEND', 45, 45),
                                                                                    ('Karen Doggenweiler', 'k.araneda@innovatech.cl', 'DEVELOPER_LEAD', 20, 45),
                                                                                    ('Julian Elfenbein', 'j.elfenbein@innovatech.cl', 'DEVELOPER_FULLSTACK', 45, 45),
                                                                                    ('Vivi Kreutzberger', 'v.elfenbein@innovatech.cl', 'DEVELOPER_QA', 15, 45),
                                                                                    ('Leo Caprile', 'l.caprile@innovatech.cl', 'DEVELOPER_CLOUD', 40, 45),
                                                                                    ('Iván Núñez', 'i.nunez@innovatech.cl', 'DEVELOPER_SECURITY', 45, 45),
                                                                                    ('Constanza Santa María', 'c.nunez@innovatech.cl', 'DEVELOPER_BACKEND', 30, 45),
                                                                                    ('Amaro Gómez-Pablos', 'a.gomez@innovatech.cl', 'DEVELOPER_FRONTEND', 45, 45),
                                                                                    ('Matías del Río', 'm.gomez@innovatech.cl', 'UX_DESIGNER_WRITER', 12, 45),
                                                                                    ('Mónica Rincón', 'm.rincon@innovatech.cl', 'DEVELOPER_DEVOPS', 45, 45),
                                                                                    ('Daniel Matamala', 'd.rincon@innovatech.cl', 'DEVELOPER_BACKEND', 25, 45),
                                                                                    ('Eduardo Fuentes', 'e.fuentes2@innovatech.cl', 'DEVELOPER_QA', 40, 45),
                                                                                    ('Jean Philippe Cretton', 'jp.cretton@innovatech.cl', 'DEVELOPER_FRONTEND', 45, 45),
                                                                                    ('Millaray Viera', 'm.cretton@innovatech.cl', 'UX_DESIGNER', 20, 45),
                                                                                    ('Pancho Saavedra', 'p.saavedra@innovatech.cl', 'DEVELOPER_COMMUNITY', 45, 45),
                                                                                    ('Jorge Zabaleta', 'j.zabaleta@innovatech.cl', 'DEVELOPER_BACKEND', 15, 45),
                                                                                    ('Belén Mora', 'b.zabaleta@innovatech.cl', 'DEVELOPER_QA', 40, 45),
                                                                                    ('Javiera Contador', 'j.contador@innovatech.cl', 'DEVELOPER_ASSISTANT', 45, 45),
                                                                                    ('Fernando Larraín', 'f.contador@innovatech.cl', 'DEVELOPER_FULLSTACK', 10, 45),
                                                                                    ('Dayana Amigo', 'd.contador@innovatech.cl', 'DEVELOPER_FRONTEND', 45, 45),
                                                                                    ('Marcial Tagle', 'm.tagle@innovatech.cl', 'DEVELOPER_CLOUD', 35, 45);